### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by doncabreraphone** [chuckhoupt/goaccess-dh#1]
Followed instructions, got error 500. Shared test server, installed under /goaccess-dh/ etc. Nothing.

**Comment by chuckhoupt** [comment]
Thanks for giving it a try. Do you see any error messages in the site's `error.log`? (in `/home/user/logs/example.com/https/error.log`).

One possibility is that the CGI scripts lost their executable bit. This could be fixed on the server with: `chmod +x example/com/goaccess-dh/*.cgi`

**Comment by doncabreraphone** [comment]
Hi, thanks for writing this script!

~~suexec policy violation is the only outstanding error there. End of script output before headers: index.cgi~~

~~I chmod the *.cgi files and is now working, but it returns a blank page (current site + "all pages" link show a blank page)~~

Scratch that. Is now working. I have another question so I will make it a new issue, will mark this one as resolved. If someone come across with the same situation, make sure the right files are executable.
